In [1]:
import os
import sys
sys.path.append(os.path.abspath(os.path.join(os.getcwd(), '..')))

import pandas as pd

from common.utils import DataPreprocessor, FeatureEngineer, set_seed
from common.exp_data_utils import ExperimentDataPreprocessor
from common.eval import Evaluator

MOVIELENS_DATA_DIR = "../datasets/hetrec2011-movielens-2k-v2/user_ratedmovies.dat"
RANDOM_SEED = 8

# Initialize data processors
set_seed(RANDOM_SEED)
data_preprocessor = DataPreprocessor()
experiment_data_preprocessor = ExperimentDataPreprocessor()
evaluator = Evaluator()

/home/adam/R11_Bai/DPRecSys/.venv/lib/python3.11/site-packages/transformers/utils/generic.py:441: FutureWarning: `torch.utils._pytree._register_pytree_node` is deprecated. Please use `torch.utils._pytree.register_pytree_node` instead.
  _torch_pytree._register_pytree_node(
Seed set to 8
Seed set to 42

random seed set to 8
numpy seed set to 8
torch seed set to 8
lightning seed set to 8
torch set to use deterministic algorithms

In [2]:
import joblib
import torch
import torch.nn.functional as F

model_name = "ngcf"
dir = f"artifacts/{model_name}"
prefix = f"{model_name}_k_all"
# eval_df = joblib.load(os.path.join(dir, f"{prefix}_eval_df.pkl"))
# user_dps_df = joblib.load(os.path.join(dir, f"user_dps_df.pkl"))
feature_engineer: FeatureEngineer = joblib.load(os.path.join(dir, f"feature_engineer.pkl"))

# Load embeddings
embeddings_dir = f"embeddings/{model_name}/"
user_emb: torch.Tensor = torch.load(f"{embeddings_dir}user_emb.pt")
item_emb: torch.Tensor = torch.load(f"{embeddings_dir}item_emb.pt")

print(user_emb.size())
print(item_emb.size())

torch.Size([2065, 256])
torch.Size([8397, 256])

In [3]:
interaction_df = data_preprocessor.load_and_process_df(
    file_dir=MOVIELENS_DATA_DIR,
    year_range=(2006, 2008),
)

interaction_info_df = data_preprocessor.join_item_features(
    df=interaction_df, actor_k=5, threshold=5,
)
interaction_info_df.head()

Data count: 855598
Data count after filtering by year (2006, 2008): 480608
Num of distinct users: 2103
Num of distinct items: 9519
done!
------------------------------
Filtering by min user/item interactions (10/0):
Data count before: 480608
Data count after: 480448
done!
------------------------------
==== Final Data Info: ====
Data Year Range: (2006, 2008)
Rating Threshold: 4.0
Num of interactions: 480448
Num of distinct users: 2064
Num of distinct items: 9519
extracting item features...
merging features...
interaction data count before merging: 480448
interaction data count after merging: 478404
done!

,userID,movieID,rating,date_day,date_month,date_year,date_hour,date_minute,date_second,timestamp,label,actorID,country,directorID,directorName,genre
0,75,3,1.0,29,10,2006,23,17,16,2006-10-29 23:17:16,0,"[jack_lemmon, walter_matthau, annmargret, burg...",USA,donald_petrie,Donald Petrie,"[Comedy, Romance, [PAD], [PAD], [PAD], [PAD], ..."
1,75,32,4.5,29,10,2006,23,23,44,2006-10-29 23:23:44,1,"[[RARE], [RARE], [RARE], [RARE], [RARE]]",USA,[RARE],Siddharth Randeria,"[Sci-Fi, Thriller, [PAD], [PAD], [PAD], [PAD],..."
2,75,110,4.0,29,10,2006,23,30,8,2006-10-29 23:30:08,1,"[mel_gibson, sophie_marceau, patrick_mcgoohan,...",USA,[RARE],Mel Gibson,"[Action, Drama, War, [PAD], [PAD], [PAD], [PAD..."
3,75,160,2.0,29,10,2006,23,16,52,2006-10-29 23:16:52,0,"[[RARE], laura_linney, ernie_hudson_jr, tim_cu...",USA,frank_marshall,Frank Marshall,"[Action, Adventure, Mystery, Sci-Fi, [PAD], [P..."
4,75,163,4.0,29,10,2006,23,29,30,2006-10-29 23:29:30,1,"[antonio_banderas, salma_hayek, 1142520-joaqui...",USA,robert_rodriguez,Robert Rodriguez,"[Action, Romance, Thriller, [PAD], [PAD], [PAD..."

In [4]:
# TODO: determine which method to use for splitting
# 1. Split by year
# 2. Stratified split by user, timestamp

train_df, valid_df, test_df = experiment_data_preprocessor.stratified_time_split(
    interaction_info_df,
    time_col="timestamp",
    train_ratio=0.64,
    val_ratio=0.16,
    test_ratio=0.20,
)

TRAIN_NUM_USERS = len(train_df["userID"].unique())
TRAIN_NUM_ITEMS = len(train_df["movieID"].unique())

Splitting data into train/valid/test by time period with ratio=(0.64 : 0.16 : 0.2):
train: 305206 (63.8%)
valid: 75578 (15.8%)
test: 97620 (20.41%)
------------------------------

Check target label distribution after splitting (%):
train label
0    0.547669
1    0.452331
Name: proportion, dtype: float64
valid label
0    0.606737
1    0.393263
Name: proportion, dtype: float64
test label
0    0.590914
1    0.409086
Name: proportion, dtype: float64

In [5]:
train_df

,userID,movieID,rating,date_day,date_month,date_year,date_hour,date_minute,date_second,timestamp,label,actorID,country,directorID,directorName,genre
0,75,2011,2.0,29,10,2006,23,16,39,2006-10-29 23:16:39,0,"[christopher_lloyd, lea_thompson, thomas_f_wil...",USA,robert_zemeckis,Robert Zemeckis,"[Action, Adventure, Comedy, Sci-Fi, [PAD], [PA..."
1,75,420,2.0,29,10,2006,23,16,42,2006-10-29 23:16:42,0,"[eddie_murphy, judge_reinhold, hector_elizondo...",USA,john_landis,John Landis,"[Action, Comedy, Crime, Thriller, [PAD], [PAD]..."
2,75,160,2.0,29,10,2006,23,16,52,2006-10-29 23:16:52,0,"[[RARE], laura_linney, ernie_hudson_jr, tim_cu...",USA,frank_marshall,Frank Marshall,"[Action, Adventure, Mystery, Sci-Fi, [PAD], [P..."
3,75,1304,2.5,29,10,2006,23,16,56,2006-10-29 23:16:56,0,"[paul_newman, robert_redford, katharine_ross, ...",USA,george_roy_hill,George Roy Hill,"[Action, Comedy, Western, [PAD], [PAD], [PAD],..."
4,75,353,3.5,29,10,2006,23,17,0,2006-10-29 23:17:00,0,"[[RARE], ernie_hudson_jr, michael_wincott, dav...",USA,[RARE],Alex Proyas,"[Action, Crime, Fantasy, Thriller, [PAD], [PAD..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
305201,71534,969,4.0,3,12,2007,2,40,41,2007-12-03 02:40:41,1,"[humphrey_bogart, katharine_hepburn, robert_mo...",UK,john_huston,John Huston,"[Adventure, Comedy, Romance, War, [PAD], [PAD]..."
305202,71534,933,5.0,3,12,2007,2,40,49,2007-12-03 02:40:49,1,"[cary_grant, grace_kelly, [RARE], 1016736-john...",USA,alfred_hitchcock,Alfred Hitchcock,"[Crime, Mystery, Romance, Thriller, [PAD], [PA..."
305203,71534,1387,4.0,3,12,2007,2,41,24,2007-12-03 02:41:24,1,"[roy_scheider, robert_shaw, narrated_by_richar...",USA,steven_spielberg,Steven Spielberg,"[Action, Horror, [PAD], [PAD], [PAD], [PAD], [..."
305204,71534,1269,4.5,3,12,2007,2,41,33,2007-12-03 02:41:33,1,"[cary_grant, [RARE], raymond_massey, [RARE], p...",USA,frank_capra,Frank Capra,"[Comedy, Mystery, Thriller, [PAD], [PAD], [PAD..."
305205,71534,40629,2.0,3,12,2007,2,41,48,2007-12-03 02:41:48,0,"[keira_knightley, [RARE], brenda_blethyn, dona...",France,[RARE],Joe Wright,"[Drama, Romance, [PAD], [PAD], [PAD], [PAD], [..."

In [6]:
encoded_df = feature_engineer.transform(train_df)
encoded_df

Transformed: Re-index user/item mapping
Transformed: Encoded idx for actorID
Transformed: Encoded idx for country
Transformed: Encoded idx for directorID
Transformed: Encoded idx for genre

,userID,movieID,rating,date_day,date_month,date_year,date_hour,date_minute,date_second,timestamp,label,directorName,actorID_idx,country_idx,directorID_idx,genre_idx
0,0,1556,2.0,29,10,2006,23,16,39,2006-10-29 23:16:39,0,Robert Zemeckis,"[443, 1384, 2127, 1, 688]",37,444,"[2, 3, 6, 17, 0, 0, 0, 0]"
1,0,361,2.0,29,10,2006,23,16,42,2006-10-29 23:16:42,0,John Landis,"[664, 1245, 903, 1, 2063]",37,258,"[2, 6, 7, 18, 0, 0, 0, 0]"
2,0,137,2.0,29,10,2006,23,16,52,2006-10-29 23:16:52,0,Frank Marshall,"[1, 1376, 726, 2140, 1]",37,162,"[2, 3, 15, 17, 0, 0, 0, 0]"
3,0,1029,2.5,29,10,2006,23,16,56,2006-10-29 23:16:56,0,George Roy Hill,"[1754, 1899, 1290, 1, 1]",37,181,"[2, 6, 20, 0, 0, 0, 0, 0]"
4,0,308,3.5,29,10,2006,23,17,0,2006-10-29 23:17:00,0,Alex Proyas,"[1, 726, 1603, 556, 1]",37,1,"[2, 7, 10, 18, 0, 0, 0, 0]"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
305201,2063,765,4.0,3,12,2007,2,40,41,2007-12-03 02:40:41,1,John Huston,"[938, 1289, 1895, 1, 2123]",36,256,"[3, 6, 16, 19, 0, 0, 0, 0]"
305202,2063,732,5.0,3,12,2007,2,40,49,2007-12-03 02:40:49,1,Alfred Hitchcock,"[370, 855, 1, 43, 1]",37,36,"[7, 15, 16, 18, 0, 0, 0, 0]"
305203,2063,1093,4.0,3,12,2007,2,41,24,2007-12-03 02:41:24,1,Steven Spielberg,"[1939, 1902, 1663, 1445, 1655]",37,494,"[2, 12, 0, 0, 0, 0, 0, 0]"
305204,2063,995,4.5,3,12,2007,2,41,33,2007-12-03 02:41:33,1,Frank Capra,"[370, 1, 1829, 1, 1777]",37,160,"[6, 15, 18, 0, 0, 0, 0, 0]"
305205,2063,7532,2.0,3,12,2007,2,41,48,2007-12-03 02:41:48,0,Joe Wright,"[1304, 1, 305, 637, 2167]",12,1,"[9, 16, 0, 0, 0, 0, 0, 0]"

In [7]:
encoded_df[["userID", "movieID"]].describe()

              userID        movieID
count  305206.000000  305206.000000
mean     1011.239402    3413.014387
std       587.578858    2616.147266
min         0.000000       0.000000
25%       506.000000    1010.000000
50%      1001.000000    2710.000000
75%      1507.000000    5748.000000
max      2063.000000    8395.000000

In [ ]:
gs_score_dict = {}
user_group = encoded_df[["userID", "movieID", "rating"]].groupby("userID")
for user_id, user_df in user_group:
    ratings = torch.tensor(user_df["rating"].tolist()).unsqueeze(1) # [m, 1]
    interacted_items = user_df["movieID"].tolist() # [m]
    interacted_item_emb = item_emb[interacted_items] # [m, d]
    center = (ratings * interacted_item_emb).sum(dim=0) / ratings.sum() # [d]

    # Normalize vectors
    item_norm = F.normalize(interacted_item_emb, dim=1)  # [m, d]
    center_norm = F.normalize(center, dim=0)  # [d]

    # Compute cosine similarities (dot products after normalization)
    cos_sim = (item_norm @ center_norm)  # [m]

    # weighted avg of cosine similarities
    gs_score = (ratings.squeeze(1) * cos_sim).sum() / ratings.sum(dim=0) # scalar
    gs_score_dict[user_id] = gs_score.item()

print(gs_score_dict)

{0: 0.40108147263526917,
 1: 0.5338392853736877,
 2: 0.48449641466140747,
 3: 0.6412871479988098,
 4: 0.5113397836685181,
 5: 0.5145062804222107,
 6: 0.5413745641708374,
 7: 0.44430384039878845,
 8: 0.6756030917167664,
 9: 0.5541414022445679,
 10: 0.6054080128669739,
 11: 0.44997599720954895,
 12: 0.6219052076339722,
 13: 0.45852386951446533,
 14: 0.6307879686355591,
 15: 0.5621853470802307,
 16: 0.5520792603492737,
 17: 0.5525197982788086,
 18: 0.39040103554725647,
 19: 0.6364222168922424,
 20: 0.6245563626289368,
 21: 0.6559170484542847,
 22: 0.41889381408691406,
 23: 0.6116979718208313,
 24: 0.4747993052005768,
 25: 0.6930024027824402,
 26: 0.7191045880317688,
 27: 0.46924054622650146,
 28: 0.5073168277740479,
 29: 0.7036046981811523,
 30: 0.5861787796020508,
 31: 0.5716935396194458,
 32: 0.5705193877220154,
 33: 0.5275953412055969,
 34: 0.30872124433517456,
 35: 0.6389622092247009,
 36: 0.3924306333065033,
 37: 0.5334354639053345,
 38: 0.5397823452949524,
 39: 0.5173454880714417,
 40: 0.4855799376964569,
 41: 0.5768399834632874,
 42: 0.4562351703643799,
 43: 0.32735732197761536,
 44: 0.6402857303619385,
 45: 0.40296289324760437,
 46: 0.42801836133003235,
 47: 0.6063998341560364,
 48: 0.5992863178253174,
 49: 0.49022945761680603,
 50: 0.608730673789978,
 51: 0.4683952033519745,
 52: 0.6004893183708191,
 53: 0.44176095724105835,
 54: 0.4872290790081024,
 55: 0.43081432580947876,
 56: 0.377224862575531,
 57: 0.6282232403755188,
 58: 0.48932090401649475,
 59: 0.44894611835479736,
 60: 0.5567401647567749,
 61: 0.5434029698371887,
 62: 0.5610976219177246,
 63: 0.7034968733787537,
 64: 0.6390482783317566,
 65: 0.6508591175079346,
 66: 0.5252817273139954,
 67: 0.570769727230072,
 68: 0.667559802532196,
 69: 0.5370861887931824,
 70: 0.41525471210479736,
 71: 0.588382363319397,
 72: 0.633144199848175,
 73: 0.627638578414917,
 74: 0.42503783106803894,
 75: 0.45171281695365906,
 76: 0.4559350609779358,
 77: 0.6261680722236633,
 78: 0.4816008508205414,
 79: 0.6683169007301331,
 80: 0.3203584551811218,
 81: 0.5533557534217834,
 82: 0.7748692035675049,
 83: 0.5426573753356934,
 84: 0.6437972187995911,
 85: 0.6466400623321533,
 86: 0.5230304002761841,
 87: 0.5502639412879944,
 88: 0.6552635431289673,
 89: 0.3548712730407715,
 90: 0.4918166995048523,
 91: 0.39630839228630066,
 92: 0.5142247080802917,
 93: 0.43656256794929504,
 94: 0.5687052607536316,
 95: 0.618323028087616,
 96: 0.4517154395580292,
 97: 0.5538120269775391,
 98: 0.24729444086551666,
 99: 0.442577064037323,
 100: 0.3616269528865814,
 101: 0.5958251357078552,
 102: 0.5011683106422424,
 103: 0.3738957345485687,
 104: 0.41156771779060364,
 105: 0.6018474102020264,
 106: 0.5898086428642273,
 107: 0.5068058371543884,
 108: 0.5452382564544678,
 109: 0.5550211071968079,
 110: 0.4157819151878357,
 111: 0.5277600288391113,
 112: 0.5356985926628113,
 113: 0.5812586545944214,
 114: 0.7892181873321533,
 115: 0.5766703486442566,
 116: 0.5245300531387329,
 117: 0.46831369400024414,
 118: 0.6286190748214722,
 119: 0.44245782494544983,
 120: 0.6328424215316772,
 121: 0.4398593008518219,
 122: 0.3541622459888458,
 123: 0.4712929427623749,
 124: 0.45275601744651794,
 125: 0.5701022148132324,
 126: 0.3305560350418091,
 127: 0.585804283618927,
 128: 0.5714399814605713,
 129: 0.4279014766216278,
 130: 0.3483006954193115,
 131: 0.5964769124984741,
 132: 0.46382245421409607,
 133: 0.5670700669288635,
 134: 0.47469213604927063,
 135: 0.6309489011764526,
 136: 0.47475874423980713,
 137: 0.5670205354690552,
 138: 0.5234457850456238,
 139: 0.4042973518371582,
 140: 0.6434425115585327,
 141: 0.5987550616264343,
 142: 0.544989824295044,
 143: 0.5221199989318848,
 144: 0.5330215096473694,
 145: 0.5594707131385803,
 146: 0.5645114779472351,
 147: 0.31573358178138733,
 148: 0.5617532134056091,
 149: 0.5232332348823547,
 150: 0.3921140432357788,
 151: 0.6122682690620422,
 152: 0.5831866264343262,
 153: 0.5803150534629822,
 154: 0.5592421293258667,
 155: 0.6218995451927185,
 156: 0.5957074165344238,
 157: 0.5750706195831299,
 158: 0.5794029235839844,
 159: 0.6412604451179504,
 160: 0.6035740971565247,
 161: 0.45742568373680115,
 162: 0.3408205807209015,
 163: 0.5524694919586182,
 164: 0.2524871826171875,
 165: 0.486727774143219,
 166: 0.550588846206665,
 167: 0.5569880604743958,
 168: 0.39488548040390015,
 169: 0.5388932824134827,
 170: 0.4779025912284851,
 171: 0.5422210693359375,
 172: 0.3547716438770294,
 173: 0.5363502502441406,
 174: 0.40107157826423645,
 175: 0.48422959446907043,
 176: 0.4848242998123169,
 177: 0.5656392574310303,
 178: 0.7125574350357056,
 179: 0.5840286612510681,
 180: 0.29166287183761597,
 181: 0.5720086693763733,
 182: 0.4600038230419159,
 183: 0.45419925451278687,
 184: 0.46442851424217224,
 185: 0.4029847979545593,
 186: 0.524163007736206,
 187: 0.45692843198776245,
 188: 0.34230270981788635,
 189: 0.5762540102005005,
 190: 0.5865013599395752,
 191: 0.5128328800201416,
 192: 0.23466120660305023,
 193: 0.5389791131019592,
 194: 0.5754119753837585,
 195: 0.5522691607475281,
 196: 0.5765727162361145,
 197: 0.5022969245910645,
 198: 0.6696146130561829,
 199: 0.35990628600120544,
 200: 0.4187517464160919,
 201: 0.44350680708885193,
 202: 0.4769713580608368,
 203: 0.5754532814025879,
 204: 0.46441951394081116,
 205: 0.6805196404457092,
 206: 0.5545483231544495,
 207: 0.3721400201320648,
 208: 0.3686634600162506,
 209: 0.6123953461647034,
 210: 0.5093142986297607,
 211: 0.5572123527526855,
 212: 0.4825078547000885,
 213: 0.3214259743690491,
 214: 0.5003146529197693,
 215: 0.306779682636261,
 216: 0.5954975485801697,
 217: 0.465180367231369,
 218: 0.5187175273895264,
 219: 0.489721417427063,
 220: 0.28394392132759094,
 221: 0.5007184147834778,
 222: 0.4886758625507355,
 223: 0.5795464515686035,
 224: 0.5616623163223267,
 225: 0.4847733676433563,
 226: 0.5004788637161255,
 227: 0.5153958797454834,
 228: 0.5921487212181091,
 229: 0.6058319211006165,
 230: 0.5905157923698425,
 231: 0.44387152791023254,
 232: 0.495999276638031,
 233: 0.6307080388069153,
 234: 0.46512162685394287,
 235: 0.557226300239563,
 236: 0.5116551518440247,
 237: 0.5181950330734253,
 238: 0.41088706254959106,
 239: 0.600781261920929,
 240: 0.3891149163246155,
 241: 0.4149022698402405,
 242: 0.5953797698020935,
 243: 0.5561729669570923,
 244: 0.44582265615463257,
 245: 0.4174310564994812,
 246: 0.367864727973938,
 247: 0.6176482439041138,
 248: 0.2171461135149002,
 249: 0.6945450901985168,
 250: 0.6303353309631348,
 251: 0.3367496728897095,
 252: 0.4891121983528137,
 253: 0.49501410126686096,
 254: 0.4839911162853241,
 255: 0.30731236934661865,
 256: 0.5044209361076355,
 257: 0.34245559573173523,
 258: 0.5995795726776123,
 259: 0.549088180065155,
 260: 0.4424545466899872,
 261: 0.6030372977256775,
 262: 0.37935468554496765,
 263: 0.6048797965049744,
 264: 0.49573540687561035,
 265: 0.4798765778541565,
 266: 0.49575114250183105,
 267: 0.5135646462440491,
 268: 0.6044225692749023,
 269: 0.5184064507484436,
 270: 0.528420627117157,
 271: 0.4716514050960541,
 272: 0.519194483757019,
 273: 0.3794809579849243,
 274: 0.46609628200531006,
 275: 0.6343908309936523,
 276: 0.43814870715141296,
 277: 0.5681741237640381,
 278: 0.6171773672103882,
 279: 0.5473129749298096,
 280: 0.3915592432022095,
 281: 0.6133263111114502,
 282: 0.4771095812320709,
 283: 0.553776204586029,
 284: 0.5389494895935059,
 285: 0.5903583765029907,
 286: 0.6841714382171631,
 287: 0.7698328495025635,
 288: 0.3502925634384155,
 289: 0.6626236438751221,
 290: 0.4606049656867981,
 291: 0.4460724890232086,
 292: 0.5720763802528381,
 293: 0.6357985138893127,
 294: 0.5088899731636047,
 295: 0.4907693564891815,
 296: 0.6143881678581238,
 297: 0.4749918580055237,
 298: 0.6019188165664673,
 299: 0.570290207862854,
 300: 0.5217396020889282,
 301: 0.4648596942424774,
 302: 0.5860700607299805,
 303: 0.5614256262779236,
 304: 0.2872925102710724,
 305: 0.6097434759140015,
 306: 0.5361136794090271,
 307: 0.6779531836509705,
 308: 0.4405154883861542,
 309: 0.6009615659713745,
 310: 0.5960619449615479,
 311: 0.5318657159805298,
 312: 0.49297282099723816,
 313: 0.5251516699790955,
 314: 0.534854531288147,
 315: 0.43265479803085327,
 316: 0.47087281942367554,
 317: 0.5772686004638672,
 318: 0.6571807861328125,
 319: 0.3266063332557678,
 320: 0.6226370930671692,
 321: 0.527851402759552,
 322: 0.5877076983451843,
 323: 0.5851539373397827,
 324: 0.6163550019264221,
 325: 0.6010454297065735,
 326: 0.5365750193595886,
 327: 0.40708890557289124,
 328: 0.5200585722923279,
 329: 0.6097061634063721,
 330: 0.5982455015182495,
 331: 0.32879146933555603,
 332: 0.4790414273738861,
 333: 0.5402258634567261,
 334: 0.6730954647064209,
 335: 0.5317586660385132,
 336: 0.5237569808959961,
 337: 0.3570064306259155,
 338: 0.6351380348205566,
 339: 0.5393993258476257,
 340: 0.5047858357429504,
 341: 0.598414421081543,
 342: 0.5326548218727112,
 343: 0.4213508367538452,
 344: 0.5631638765335083,
 345: 0.4547172784805298,
 346: 0.5269781947135925,
 347: 0.471697598695755,
 348: 0.5583084225654602,
 349: 0.5227543115615845,
 350: 0.6580039262771606,
 351: 0.4939815104007721,
 352: 0.5445786118507385,
 353: 0.6118785738945007,
 354: 0.3321128487586975,
 355: 0.4333534240722656,
 356: 0.5601562857627869,
 357: 0.6586725115776062,
 358: 0.6151512861251831,
 359: 0.49364182353019714,
 360: 0.57125324010849,
 361: 0.7200928330421448,
 362: 0.4816623032093048,
 363: 0.6086206436157227,
 364: 0.3554759621620178,
 365: 0.5765722393989563,
 366: 0.585383415222168,
 367: 0.4754994809627533,
 368: 0.32843732833862305,
 369: 0.6186891794204712,
 370: 0.5309608578681946,
 371: 0.6448692679405212,
 372: 0.5158023238182068,
 373: 0.5083448886871338,
 374: 0.38331151008605957,
 375: 0.5183207392692566,
 376: 0.4798160493373871,
 377: 0.522635817527771,
 378: 0.4354839324951172,
 379: 0.2523050010204315,
 380: 0.613589346408844,
 381: 0.6191244721412659,
 382: 0.43699905276298523,
 383: 0.48268425464630127,
 384: 0.5565810203552246,
 385: 0.5764845013618469,
 386: 0.5652998685836792,
 387: 0.3555713891983032,
 388: 0.6641995906829834,
 389: 0.684138298034668,
 390: 0.5057621598243713,
 391: 0.4338182508945465,
 392: 0.6197482347488403,
 393: 0.677803635597229,
 394: 0.543907880783081,
 395: 0.44284436106681824,
 396: 0.4104609787464142,
 397: 0.34996867179870605,
 398: 0.5049887299537659,
 399: 0.5229644775390625,
 400: 0.43383631110191345,
 401: 0.41195887327194214,
 402: 0.6057506203651428,
 403: 0.5120646357536316,
 404: 0.4025951325893402,
 405: 0.46508726477622986,
 406: 0.6283923983573914,
 407: 0.6356872916221619,
 408: 0.6181367635726929,
 409: 0.7420840859413147,
 410: 0.3688655197620392,
 411: 0.7101752161979675,
 412: 0.5776774287223816,
 413: 0.4559999704360962,
 414: 0.6358674168586731,
 415: 0.4273313581943512,
 416: 0.5155322551727295,
 417: 0.5011373162269592,
 418: 0.6563653349876404,
 419: 0.637759268283844,
 420: 0.618421733379364,
 421: 0.5478489398956299,
 422: 0.6056444048881531,
 423: 0.44036176800727844,
 424: 0.6184899210929871,
 425: 0.5127485394477844,
 426: 0.628591001033783,
 427: 0.5495659112930298,
 428: 0.6181309819221497,
 429: 0.4474203884601593,
 430: 0.45453280210494995,
 431: 0.45475274324417114,
 432: 0.5686860084533691,
 433: 0.3089219331741333,
 434: 0.5306338667869568,
 435: 0.6538434624671936,
 436: 0.7543648481369019,
 437: 0.39285746216773987,
 438: 0.7054135799407959,
 439: 0.5463052988052368,
 440: 0.5254057049751282,
 441: 0.5336326956748962,
 442: 0.32585257291793823,
 443: 0.6674882173538208,
 444: 0.7184677124023438,
 445: 0.5215404033660889,
 446: 0.3669086694717407,
 447: 0.4482235610485077,
 448: 0.43418246507644653,
 449: 0.7452430129051208,
 450: 0.6678059697151184,
 451: 0.5732204914093018,
 452: 0.5205433368682861,
 453: 0.5434534549713135,
 454: 0.3591475188732147,
 455: 0.6142788529396057,
 456: 0.5394753217697144,
 457: 0.4285770654678345,
 458: 0.5548783540725708,
 459: 0.490701287984848,
 460: 0.4598003923892975,
 461: 0.5996145009994507,
 462: 0.6825768947601318,
 463: 0.602980375289917,
 464: 0.5464487075805664,
 465: 0.5480955243110657,
 466: 0.6060872673988342,
 467: 0.4719034731388092,
 468: 0.31085148453712463,
 469: 0.3817312717437744,
 470: 0.4969341456890106,
 471: 0.44144079089164734,
 472: 0.5226776599884033,
 473: 0.4769101142883301,
 474: 0.3728844225406647,
 475: 0.45694035291671753,
 476: 0.5751838684082031,
 477: 0.5626817941665649,
 478: 0.579369843006134,
 479: 0.5040605068206787,
 480: 0.5482908487319946,
 481: 0.6650828719139099,
 482: 0.4323594570159912,
 483: 0.38937994837760925,
 484: 0.49101197719573975,
 485: 0.5553044080734253,
 486: 0.686159074306488,
 487: 0.6098394989967346,
 488: 0.7251161932945251,
 489: 0.6632081866264343,
 490: 0.496841162443161,
 491: 0.4655817747116089,
 492: 0.5264736413955688,
 493: 0.4411211907863617,
 494: 0.5682568550109863,
 495: 0.6287692785263062,
 496: 0.42845261096954346,
 497: 0.5513067245483398,
 498: 0.46861547231674194,
 499: 0.4320090711116791,
 500: 0.5884597301483154,
 501: 0.31291505694389343,
 502: 0.3918098509311676,
 503: 0.6048910021781921,
 504: 0.7210755944252014,
 505: 0.5449995398521423,
 506: 0.6802270412445068,
 507: 0.4560023844242096,
 508: 0.5453052520751953,
 509: 0.6349502205848694,
 510: 0.5606978535652161,
 511: 0.5967432260513306,
 512: 0.31502774357795715,
 513: 0.6325448155403137,
 514: 0.7331464290618896,
 515: 0.3545164167881012,
 516: 0.4769427180290222,
 517: 0.358280748128891,
 518: 0.4984225332736969,
 519: 0.4066811501979828,
 520: 0.583899736404419,
 521: 0.506747305393219,
 522: 0.6361141204833984,
 523: 0.4075232148170471,
 524: 0.3277945816516876,
 525: 0.4508301615715027,
 526: 0.5434697866439819,
 527: 0.5451953411102295,
 528: 0.6618968844413757,
 529: 0.41848668456077576,
 530: 0.587532639503479,
 531: 0.4927237331867218,
 532: 0.607166588306427,
 533: 0.4196733832359314,
 534: 0.546515166759491,
 535: 0.5867466330528259,
 536: 0.5513151288032532,
 537: 0.4259900152683258,
 538: 0.5659610629081726,
 539: 0.7035685181617737,
 540: 0.5772010087966919,
 541: 0.5481653213500977,
 542: 0.7212554812431335,
 543: 0.5938116312026978,
 544: 0.35951000452041626,
 545: 0.36416587233543396,
 546: 0.5475152134895325,
 547: 0.5195679068565369,
 548: 0.5919328331947327,
 549: 0.601128339767456,
 550: 0.645172655582428,
 551: 0.4598495364189148,
 552: 0.45151466131210327,
 553: 0.6377336382865906,
 554: 0.47076302766799927,
 555: 0.5839970707893372,
 556: 0.40531763434410095,
 557: 0.6469764113426208,
 558: 0.36744067072868347,
 559: 0.42497920989990234,
 560: 0.5837467312812805,
 561: 0.5287880301475525,
 562: 0.45387259125709534,
 563: 0.567830502986908,
 564: 0.4559428095817566,
 565: 0.4772779643535614,
 566: 0.5856228470802307,
 567: 0.511773943901062,
 568: 0.6809963583946228,
 569: 0.3879176378250122,
 570: 0.5992491245269775,
 571: 0.6410526037216187,
 572: 0.48242413997650146,
 573: 0.6023551225662231,
 574: 0.43251925706863403,
 575: 0.3370125889778137,
 576: 0.6015554666519165,
 577: 0.5454776883125305,
 578: 0.636802077293396,
 579: 0.43381884694099426,
 580: 0.28617554903030396,
 581: 0.48517534136772156,
 582: 0.4316537380218506,
 583: 0.6454756259918213,
 584: 0.506500244140625,
 585: 0.4842396676540375,
 586: 0.6548693776130676,
 587: 0.4408489465713501,
 588: 0.4698633551597595,
 589: 0.5356987714767456,
 590: 0.4562240540981293,
 591: 0.4084748923778534,
 592: 0.43430694937705994,
 593: 0.5568240880966187,
 594: 0.5553626418113708,
 595: 0.19355811178684235,
 596: 0.7043765783309937,
 597: 0.3936363756656647,
 598: 0.65900719165802,
 599: 0.4956628680229187,
 600: 0.5569478869438171,
 601: 0.5054206252098083,
 602: 0.6087711453437805,
 603: 0.4813476502895355,
 604: 0.5253753066062927,
 605: 0.4984607994556427,
 606: 0.5752506256103516,
 607: 0.6227914094924927,
 608: 0.5640794038772583,
 609: 0.7063772082328796,
 610: 0.2596167325973511,
 611: 0.5333433747291565,
 612: 0.5047386288642883,
 613: 0.574970543384552,
 614: 0.6302269101142883,
 615: 0.6099913716316223,
 616: 0.5097360610961914,
 617: 0.7022414207458496,
 618: 0.4934362471103668,
 619: 0.513241708278656,
 620: 0.748889148235321,
 621: 0.4588630199432373,
 622: 0.4683379828929901,
 623: 0.3830464780330658,
 624: 0.5523884892463684,
 625: 0.4117175340652466,
 626: 0.3995770215988159,
 627: 0.5951115489006042,
 628: 0.41159793734550476,
 629: 0.6425579786300659,
 630: 0.5964469313621521,
 631: 0.6706032752990723,
 632: 0.5290833115577698,
 633: 0.6534639596939087,
 634: 0.3853612244129181,
 635: 0.38362473249435425,
 636: 0.6200429797172546,
 637: 0.5658121705055237,
 638: 0.5813232064247131,
 639: 0.611911416053772,
 640: 0.3893945813179016,
 641: 0.2861597239971161,
 642: 0.5701563358306885,
 643: 0.616624653339386,
 644: 0.5662792325019836,
 645: 0.614437997341156,
 646: 0.6233916878700256,
 647: 0.4040013253688812,
 648: 0.4642429053783417,
 649: 0.5116888284683228,
 650: 0.46635109186172485,
 651: 0.6932969093322754,
 652: 0.38410094380378723,
 653: 0.37217748165130615,
 654: 0.43972066044807434,
 655: 0.5291228890419006,
 656: 0.46868976950645447,
 657: 0.585425853729248,
 658: 0.5846590995788574,
 659: 0.43251651525497437,
 660: 0.5067936182022095,
 661: 0.42279189825057983,
 662: 0.49772319197654724,
 663: 0.6111771464347839,
 664: 0.5392263531684875,
 665: 0.6338626742362976,
 666: 0.6045249104499817,
 667: 0.37613314390182495,
 668: 0.5258273482322693,
 669: 0.4347098171710968,
 670: 0.6147636771202087,
 671: 0.47653549909591675,
 672: 0.5630314946174622,
 673: 0.40433481335639954,
 674: 0.36367329955101013,
 675: 0.46877390146255493,
 676: 0.315475732088089,
 677: 0.7069937586784363,
 678: 0.4882303774356842,
 679: 0.43544358015060425,
 680: 0.5903164744377136,
 681: 0.40548786520957947,
 682: 0.46276482939720154,
 683: 0.45305073261260986,
 684: 0.3786046802997589,
 685: 0.4441436529159546,
 686: 0.543385922908783,
 687: 0.5925458073616028,
 688: 0.5858359336853027,
 689: 0.6332303285598755,
 690: 0.3422783315181732,
 691: 0.4707094430923462,
 692: 0.5751436948776245,
 693: 0.24993686378002167,
 694: 0.42837631702423096,
 695: 0.5359307527542114,
 696: 0.38754814863204956,
 697: 0.560688316822052,
 698: 0.5364789962768555,
 699: 0.5644203424453735,
 700: 0.6778125762939453,
 701: 0.3585878014564514,
 702: 0.5437647700309753,
 703: 0.2760009169578552,
 704: 0.376985639333725,
 705: 0.5872191786766052,
 706: 0.6190632581710815,
 707: 0.6830249428749084,
 708: 0.56655353307724,
 709: 0.5355237126350403,
 710: 0.3177124559879303,
 711: 0.5449150800704956,
 712: 0.565319299697876,
 713: 0.573157787322998,
 714: 0.5238258242607117,
 715: 0.5429255366325378,
 716: 0.6031132936477661,
 717: 0.5690364241600037,
 718: 0.5214268565177917,
 719: 0.5772312879562378,
 720: 0.35971829295158386,
 721: 0.3616503179073334,
 722: 0.5245159864425659,
 723: 0.5006046891212463,
 724: 0.5442482829093933,
 725: 0.6235716938972473,
 726: 0.505002498626709,
 727: 0.33295899629592896,
 728: 0.447516530752182,
 729: 0.5154590010643005,
 730: 0.5575885772705078,
 731: 0.4796483516693115,
 732: 0.5795246362686157,
 733: 0.5682901740074158,
 734: 0.5530528426170349,
 735: 0.35195496678352356,
 736: 0.4950966238975525,
 737: 0.5657422542572021,
 738: 0.5368677377700806,
 739: 0.6287452578544617,
 740: 0.552310585975647,
 741: 0.33531254529953003,
 742: 0.30358174443244934,
 743: 0.4469231963157654,
 744: 0.6256424784660339,
 745: 0.4527988135814667,
 746: 0.4188448488712311,
 747: 0.5732447504997253,
 748: 0.5410444140434265,
 749: 0.6067997813224792,
 750: 0.6448425650596619,
 751: 0.6249098777770996,
 752: 0.5062560439109802,
 753: 0.39351406693458557,
 754: 0.30129435658454895,
 755: 0.625934898853302,
 756: 0.4744662046432495,
 757: 0.4321991205215454,
 758: 0.46222367882728577,
 759: 0.6934248208999634,
 760: 0.5111517310142517,
 761: 0.5124465227127075,
 762: 0.5896018743515015,
 763: 0.5683585405349731,
 764: 0.5424444675445557,
 765: 0.597885012626648,
 766: 0.4972793161869049,
 767: 0.6163720488548279,
 768: 0.4771282970905304,
 769: 0.5277952551841736,
 770: 0.5397036075592041,

In [18]:
user_type = {"encoded_generalist": [], "encoded_specialist": []}
for user_id, gs_score in gs_score_dict.items():
    if gs_score <= 0.5:
        user_type["encoded_generalist"].append(user_id)
    else:
        user_type["encoded_specialist"].append(user_id)

user_type["generalist"] = [feature_engineer.idx2vocab['userID'][user_id] for user_id in user_type["encoded_generalist"]]
user_type["specialist"] = [feature_engineer.idx2vocab['userID'][user_id] for user_id in user_type["encoded_specialist"]]

print(user_type.keys())

dict_keys(['encoded_generalist', 'encoded_specialist', 'generalist', 'specialist'])

In [19]:
dir = "artifacts/"
joblib.dump(user_type, os.path.join(dir, 'user_gs_type_dict.pkl'))

['artifacts/user_gs_type_dict.pkl']

In [21]:
loaded_dict = joblib.load(os.path.join(dir, 'user_gs_type_dict.pkl'))
print(loaded_dict.keys())

dict_keys(['encoded_generalist', 'encoded_specialist', 'generalist', 'specialist'])